from . import restaurant_allergen
from . import restaurant_scrap_reason
from . import restaurant_recipe
from . import mrp_bom_line
from . import restaurant_kds_order
from . import par_level
from . import franchise
from . import restaurant_kpi
from . import pos_config
from . import pos_order
from . import pos_order_line
from . import stock_scrap
