import logging
from datetime import date

from odoo import api, fields, models

_logger = logging.getLogger(__name__)


class ParLevel(models.Model):
    _name = 'restaurant.par.level'
    _description = 'PAR Level - Periodic Automatic Replenishment'
    _order = 'location_id, product_id'

    product_id = fields.Many2one('product.product', required=True, ondelete='cascade', index=True)
    location_id = fields.Many2one(
        'stock.location',
        required=True,
        ondelete='cascade',
        domain=[('usage', '=', 'internal')],
    )
    par_qty = fields.Float(string='PAR Quantity', digits='Product Unit of Measure')
    min_qty = fields.Float(string='Reorder Point', digits='Product Unit of Measure')
    uom_id = fields.Many2one('uom.uom', related='product_id.uom_po_id', readonly=True)
    supplier_id = fields.Many2one('res.partner', domain=[('supplier_rank', '>', 0)])
    lead_time = fields.Integer(string='Lead Time (days)', default=1)
    last_po_date = fields.Date(readonly=True)
    active = fields.Boolean(default=True)
    company_id = fields.Many2one('res.company', default=lambda self: self.env.company)

    current_stock = fields.Float(compute='_compute_current_stock', store=False)
    needs_reorder = fields.Boolean(compute='_compute_current_stock', store=False)

    _sql_constraints = [
        (
            'par_unique_product_location_company',
            'UNIQUE(product_id, location_id, company_id)',
            'Only one PAR record per product/location/company is allowed.',
        ),
    ]

    def _compute_current_stock(self):
        for rec in self:
            stock = rec._get_current_stock()
            rec.current_stock = stock
            rec.needs_reorder = stock < rec.min_qty

    def _get_current_stock(self):
        self.ensure_one()
        quants = self.env['stock.quant'].search(
            [
                ('product_id', '=', self.product_id.id),
                ('location_id', '=', self.location_id.id),
                ('company_id', '=', self.company_id.id),
            ]
        )
        return sum(quants.mapped('quantity'))

    @api.model
    def generate_purchase_orders(self):
        records = self.search([('active', '=', True)])
        to_reorder = [r for r in records if r._get_current_stock() < r.min_qty]
        if not to_reorder:
            _logger.info('PAR cron: no reorders needed.')
            return

        groups = {}
        for rec in to_reorder:
            key = (rec.supplier_id.id or 0, rec.company_id.id)
            groups.setdefault(key, []).append(rec)

        for (supplier_id, company_id), recs in groups.items():
            if not supplier_id:
                _logger.warning('PAR: no supplier for %s - skipped.', [r.product_id.display_name for r in recs])
                continue
            self._create_purchase_order(supplier_id, company_id, recs)

        self.browse([r.id for r in to_reorder]).write({'last_po_date': date.today()})
        _logger.info('PAR cron: processed %d product(s).', len(to_reorder))

    def _create_purchase_order(self, supplier_id, company_id, par_records):
        po = self.env['purchase.order'].search(
            [
                ('partner_id', '=', supplier_id),
                ('company_id', '=', company_id),
                ('state', '=', 'draft'),
            ],
            limit=1,
        )
        if not po:
            po = self.env['purchase.order'].create(
                {
                    'partner_id': supplier_id,
                    'company_id': company_id,
                    'notes': 'Auto-generated by Restaurant Suite PAR replenishment.',
                }
            )

        lines_created = 0
        for rec in par_records:
            current = rec._get_current_stock()
            order_qty = rec.par_qty - current
            if order_qty <= 0:
                continue
            seller = rec.product_id._select_seller(
                partner_id=rec.supplier_id,
                quantity=order_qty,
                date=fields.Date.today(),
                uom_id=rec.uom_id,
            )
            price = seller.price if seller else rec.product_id.standard_price
            self.env['purchase.order.line'].create(
                {
                    'order_id': po.id,
                    'product_id': rec.product_id.id,
                    'product_qty': order_qty,
                    'product_uom': rec.uom_id.id,
                    'price_unit': price,
                    'date_planned': fields.Datetime.now(),
                    'name': rec.product_id.display_name,
                }
            )
            lines_created += 1

        if lines_created:
            po.message_post(body=f'PAR auto-replenishment: {lines_created} product(s) below minimum.')
        return po
